EduSphere/Controllers/CompaniesController.cs
using EduSphere.Data.Services;
using EduSphere.Data.Static;
using EduSphere.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace EduSphere.Controllers
{
    [Authorize(Roles = UserRoles.Admin)]
    public class CompaniesController : Controller
    {
        private readonly ICompaniesService _service;

        public CompaniesController(ICompaniesService service)
        {
            _service = service;
        }

        [AllowAnonymous]
        public async Task<IActionResult> Index()
        {
            var allCompanies = await _service.GetAllAsync();
            return View(allCompanies);
        }

        // GET: Companies/Create
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create([Bind("Logo,Name,Description,Address,EmailAddress,PhoneNumber,WebsiteAddress")] Company company)
        {
            if (!ModelState.IsValid) return View(company);
            await _service.AddAsync(company);
            return RedirectToAction(nameof(Index));
        }

        // GET: Companies/Details/1
        [AllowAnonymous]
        public async Task<IActionResult> Details(int id)
        {
            var companyDetails = await _service.GetByIdAsync(id);
            if (companyDetails == null) return View("NotFound");
            return View(companyDetails);
        }

        // GET: Companies/Edit/1
        public async Task<IActionResult> Edit(int id)
        {
            var companyDetails = await _service.GetByIdAsync(id);
            if (companyDetails == null) return View("NotFound");
            return View(companyDetails);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Logo,Name,Description,Address,EmailAddress,PhoneNumber,WebsiteAddress")] Company company)
        {
            if (!ModelState.IsValid) return View(company);
            await _service.UpdateAsync(id, company);
            return RedirectToAction(nameof(Index));
        }

        // GET: Companies/Delete/1
        public async Task<IActionResult> Delete(int id)
        {
            var companyDetails = await _service.GetByIdAsync(id);
            if (companyDetails == null) return View("NotFound");
            return View(companyDetails);
        }

        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirm(int id)
        {
            var companyDetails = await _service.GetByIdAsync(id);
            if (companyDetails == null) return View("NotFound");

            await _service.DeleteAsync(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

EduSphere/Controllers/CoursesController.cs
using EduSphere.Data;
using EduSphere.Data.Services;
using EduSphere.Data.Services.Courses;
using EduSphere.Data.Static;
using EduSphere.Data.ViewModels;
using EduSphere.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace EduSphere.Controllers
{
    [Authorize(Roles = UserRoles.Admin)]
    public class CoursesController : Controller
    {
        private readonly ICoursesService _service;

        public CoursesController(ICoursesService service)
        {
            _service = service;
        }

        [AllowAnonymous]
        public async Task<IActionResult> Index()
        {
            var allCourses = await _service.GetAllAsync(n => n.Company);
            return View(allCourses);
        }

        [AllowAnonymous]
        public async Task<IActionResult> Filter(string searchString)
        {
            var allCourses = await _service.GetAllAsync(n => n.Company);

            if (!string.IsNullOrEmpty(searchString))
            {
                var filteredCourses = allCourses.Where(n => n.Name.Contains(searchString, StringComparison.OrdinalIgnoreCase) || n.Description.Contains(searchString, StringComparison.OrdinalIgnoreCase)).ToList();

                return View("Index", filteredCourses);
            }

            return View("Index", allCourses);
        }

        //GET: Courses/Details/1
        [AllowAnonymous]
        public async Task<IActionResult> Details(int id)
        {
            var courseDetail = await _service.GetCourseByIdAsync(id);
            return View(courseDetail);
        }

        //GET: Courses/Create
        public async Task<IActionResult> Create()
        {
            var courseDropdownsData = await _service.GetNewCourseDropdownsValues();

            ViewBag.Companies = new SelectList(courseDropdownsData.Companies, "Id", "Name");
            ViewBag.Teachers = new SelectList(courseDropdownsData.Teachers, "Id", "FullName");

            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(NewCourseVM course)
        {
            if (!ModelState.IsValid)
            {
                var courseDropdownsData = await _service.GetNewCourseDropdownsValues();

                ViewBag.Companies = new SelectList(courseDropdownsData.Companies, "Id", "Name");
                ViewBag.Teachers = new SelectList(courseDropdownsData.Teachers, "Id", "FullName");

                return View(course);
            }

            await _service.AddNewCourseAsync(course);
            return RedirectToAction(nameof(Index));
        }


        //GET: Courses/Edit/1
        public async Task<IActionResult> Edit(int id)
        {
            var courseDetails = await _service.GetCourseByIdAsync(id);
            if (courseDetails == null) return View("NotFound");

            var response = new NewCourseVM()
            {
                Id = courseDetails.Id,
                Name = courseDetails.Name,
                Description = courseDetails.Description,
                Price = courseDetails.Price,
                StartDate = courseDetails.StartDate,
                EndDate = courseDetails.EndDate,
                ImageUrl = courseDetails.ImageUrl,
                CourseCategory = courseDetails.CourseCategory,
                CompanyId = courseDetails.CompanyId,
                TeacherIds = courseDetails.Teachers_Courses.Select(n => n.TeacherId).ToList()
            };

            var courseDropdownsData = await _service.GetNewCourseDropdownsValues();
            ViewBag.Companies = new SelectList(courseDropdownsData.Companies, "Id", "Name");
            ViewBag.Teachers = new SelectList(courseDropdownsData.Teachers, "Id", "FullName");

            return View(response);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, NewCourseVM course)
        {
            if (id != course.Id) return View("NotFound");

            if (!ModelState.IsValid)
            {
                var courseDropdownsData = await _service.GetNewCourseDropdownsValues();

                ViewBag.Companies = new SelectList(courseDropdownsData.Companies, "Id", "Name");
                ViewBag.Teachers = new SelectList(courseDropdownsData.Teachers, "Id", "FullName");

                return View(course);
            }

            await _service.UpdateCourseAsync(course);
            return RedirectToAction(nameof(Index));
        }
    }
}

EduSphere/Controllers/OrdersController.cs
using EduSphere.Data.Cart;
using EduSphere.Data.Services;
using EduSphere.Data.Services.Courses;
using EduSphere.Data.ViewModels;
using EduSphere.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Security.Claims;
using System.Threading.Tasks;

namespace EduSphere.Controllers
{
    [Authorize]
    public class OrdersController : Controller
    {
        private readonly IOrdersService _ordersService;
        private readonly ShoppingCart _shoppingCart;
        private readonly ICoursesService _coursesService;

        public OrdersController(IOrdersService ordersService, ShoppingCart shoppingCart, ICoursesService coursesService)
        {
            _ordersService = ordersService;
            _shoppingCart = shoppingCart;
            _coursesService = coursesService;
        }

        public async Task<IActionResult> Index()
        {
            string userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            string userRole = User.FindFirstValue(ClaimTypes.Role);

            var orders = await _ordersService.GetOrdersByUserIdAndRoleAsync(userId, userRole);
            return View(orders);
        }

        public IActionResult ShoppingCart()
        {
            var items = _shoppingCart.GetShoppingCartItems();
            _shoppingCart.ShoppingCartItems = items;

            var response = new ShoppingCartVM()
            {
                ShoppingCart = _shoppingCart,
                ShoppingCartTotal = _shoppingCart.GetShoppingCartTotal()
            };

            return View(response);
        }

        public async Task<IActionResult> AddItemToShoppingCart(int id)
        {
            var item = await _coursesService.GetCourseByIdAsync(id);

            if (item != null)
            {
                _shoppingCart.AddItemToCart(item);
            }
            return RedirectToAction(nameof(ShoppingCart));
        }

        public async Task<IActionResult> RemoveItemFromShoppingCart(int id)
        {
            var item = await _coursesService.GetCourseByIdAsync(id);

            if (item != null)
            {
                _shoppingCart.RemoveItemFromCart(item);
            }
            return RedirectToAction(nameof(ShoppingCart));
        }

        public async Task<IActionResult> CompleteOrder()
        {
            var items = _shoppingCart.GetShoppingCartItems();
            string userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            string userEmailAddress = User.FindFirstValue(ClaimTypes.Email);

            await _ordersService.StoreOrderAsync(items, userId, userEmailAddress);
            await _shoppingCart.ClearShoppingCartAsync();

            return View("OrderCompleted");
        }
    }
}

EduSphere/Controllers/TeachersController.cs
using EduSphere.Data.Services;
using EduSphere.Data.Services.Teachers;
using EduSphere.Data.Static;
using EduSphere.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace EduSphere.Controllers
{
    [Authorize(Roles = UserRoles.Admin)]
    public class TeachersController : Controller
    {
        private readonly ITeachersService _service;

        public TeachersController(ITeachersService service)
        {
            _service = service;
        }

        [AllowAnonymous]
        public async Task<IActionResult> Index()
        {
            var teachers = await _service.GetAllAsync();
            return View(teachers);
        }

        // GET: Teachers/Create
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create([Bind("FullName, ProfilePictureURL, Specialization, Biography, PhoneNumber, EmailAddress, LinkedinProfileUrl, InstagramProfileUrl, FacebookProfileUrl")] Teacher teacher)
        {
            if (!ModelState.IsValid)
            {
                return View(teacher);
            }

            await _service.AddAsync(teacher);
            return RedirectToAction(nameof(Index));
        }

        // GET: Teachers/Details/5
        [AllowAnonymous]
        public async Task<IActionResult> Details(int id)
        {
            var teacher = await _service.GetByIdAsync(id);
            if (teacher == null)
            {
                return View("NotFound");
            }
            return View(teacher);
        }

        // GET: Teachers/Edit/5
        public async Task<IActionResult> Edit(int id)
        {
            var teacher = await _service.GetByIdAsync(id);
            if (teacher == null)
            {
                return View("NotFound");
            }
            return View(teacher);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, [Bind("Id, FullName, ProfilePictureURL, Specialization, Biography, PhoneNumber, EmailAddress, LinkedinProfileUrl, InstagramProfileUrl, FacebookProfileUrl")] Teacher teacher)
        {
            if (!ModelState.IsValid)
            {
                return View(teacher);
            }

            await _service.UpdateAsync(id, teacher);
            return RedirectToAction(nameof(Index));
        }

        // GET: Teachers/Delete/5
        public async Task<IActionResult> Delete(int id)
        {
            var teacher = await _service.GetByIdAsync(id);
            if (teacher == null)
            {
                return View("NotFound");
            }
            return View(teacher);
        }

        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var teacher = await _service.GetByIdAsync(id);
            if (teacher == null)
            {
                return View("NotFound");
            }

            await _service.DeleteAsync(id);
            return RedirectToAction(nameof(Index));
        }
    }
}
 

EduSphere/Views/Shared/NotFound.cshtml
<div class="row">
    <div class="col-md-6 offset-3">
        <h1 class="text-info">You've reached the end of the internet</h1>
        <hr />
        <a class="btn btn-outline-success" asp-controller="Courses" asp-action="Index">Home Page</a>
    </div>
</div>

EduSphere/Views/Shared/_CreateItem.cshtml
@model string

@if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
{
    <div style="position: fixed; right: 25px; bottom: 25px;" class="text-white">
        <a asp-controller="@Model" asp-action="Create" class="btn btn-success">
            <i class="bi bi-plus-circle"></i> Add New
        </a>
    </div>
}

EduSphere/Views/Shared/_Identity.cshtml
@using Microsoft.AspNetCore.Identity
@inject UserManager<ApplicationUser> UserManager;

@if (!User.Identity.IsAuthenticated)
{
    <a class="btn btn-outline-success my-2 my-sm-0" asp-controller="Account" asp-action="Login">
        <i class="bi bi-box-arrow-in-right"></i> Log in
    </a>
    <span style="padding: 5px;"></span>

    <a class="btn btn-outline-primary my-2 my-sm-0" asp-controller="Account" asp-action="Register">
        <i class="bi bi-person-plus"></i> Sign up
    </a>
}
else
{
    <div class="dropdown">
        <button class="btn btn-outline-success dropdown-toggle" type="button" id="profile-btn" data-bs-toggle="dropdown"
                aria-expanded="false">
            <i class="bi bi-person-badge"></i> @UserManager.GetUserName(User)
        </button>
        <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="profile-btn">
            <li>
                <a class="dropdown-item" asp-controller="Orders" asp-action="Index">
                    <i class="bi bi-list"></i> Orders
                </a>
            </li>
            <li>
                <a class="dropdown-item" asp-controller="Account" asp-action="UserProfile">
                    <i class="bi bi-person"></i> Profile
                </a>
            </li>
            @if (User.IsInRole("Admin"))
            {
                <li>
                    <a class="dropdown-item" asp-controller="Account" asp-action="Users">
                        <i class="bi bi-people"></i> Users
                    </a>
                </li>
            }
            <li>
                <form asp-controller="Account" asp-action="Logout">
                    <button type="submit" class="dropdown-item">
                        <i class="bi bi-box-arrow-right"></i> Log out
                    </button>
                </form>
            </li>
        </ul>
    </div>
}

EduSphere/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - EduSphere</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Courses" asp-action="Index">EduSphere</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Courses" asp-action="Index"><i class="bi bi-journal"></i> Courses</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Teachers" asp-action="Index"><i class="bi bi-person"></i> Teachers</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Companies" asp-action="Index"><i class="bi bi-building"></i> Companies</a>
                        </li>
                    </ul>
                    <form class="d-flex me-2" asp-controller="Courses" asp-action="Filter">
                        <input name="searchString" type="text" class="form-control me-2" placeholder="Search for a course..." aria-label="Search">
                        <button class="btn btn-outline-success" type="submit"><i class="bi bi-search"></i></button>
                    </form>
                    <ul class="navbar-nav">
                        @await Component.InvokeAsync("ShoppingCartSummary")
                    </ul>
                    <partial name="_Identity.cshtml" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container mt-4">
        <main role="main">
            @RenderBody()
        </main>
    </div>
    <footer class="border-top footer text-muted text-center">
        <div class="container" style="height: 40px; line-height: 40px;">
            &copy; 2024 - EduSphere
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>